### ISSUE TITLE
Do we have to mess up our golang paths to run this?

### ISSUE THREAD

**Issue by gedw99** [vanadium/core#1]
Just wondering if you can make this work without messing with our golang paths ?
Sorry to be picky, but I guess I am one of those gophers that likes the fact that you were not requiring Jiri and all that baggage.

**Comment by razvanm** [comment]
Unlike the full Vanadium this doesn't require Jiri. In a regular Go workspace all you need to do is 

```
git clone https://github.com/vanadium/core.git src/v.io
```

Is that what you tried and didn't work?

**Comment by joeblew99** [comment]
Yes thats what i tried and did not work :)

So stuff on your machine is not on mine :)

protoc and leveldb perhaps.
here goes:

````
x-MacBook-Pro:md apple$ cd try
x-MacBook-Pro:try apple$ ls
_readme.md		dmg			dmg-create		docker-pcli		eco-json-schema-form	electron		electron-control	flutter			flutter-game		localize		shop
x-MacBook-Pro:try apple$ mkdir vanadium
x-MacBook-Pro:try apple$ cd vanadium/
x-MacBook-Pro:vanadium apple$ git clone https://github.com/vanadium/core.git src/v.io
Cloning into 'src/v.io'...
remote: Counting objects: 2787, done.
remote: Total 2787 (delta 0), reused 0 (delta 0), pack-reused 2787
Receiving objects: 100% (2787/2787), 4.58 MiB | 992.00 KiB/s, done.
Resolving deltas: 100% (431/431), done.
Checking connectivity... done.
x-MacBook-Pro:vanadium apple$ go get -t v.io/...
# v.io/x/ref/services/syncbase/store/leveldb
../../../../../v.io/x/ref/services/syncbase/store/leveldb/db.go:10:11: fatal error: 'leveldb/c.h' file not found
 #include "leveldb/c.h"
          ^
1 error generated.
# google.golang.org/cloud/bigtable/internal/data_proto
../../../../../google.golang.org/cloud/bigtable/internal/data_proto/data.pb.go:1916: undefined: proto.RegisterFile
# google.golang.org/cloud/bigtable/internal/common_proto
../../../../../google.golang.org/cloud/bigtable/internal/common_proto/common.pb.go:60: undefined: proto.RegisterFile
# google.golang.org/cloud/bigtable/internal/table_data_proto
../../../../../google.golang.org/cloud/bigtable/internal/table_data_proto/table.pb.go:450: undefined: proto.RegisterFile
# google.golang.org/cloud/bigtable/internal/rpc_status_proto
../../../../../google.golang.org/cloud/bigtable/internal/rpc_status_proto/status.pb.go:113: undefined: proto.RegisterFile
x-MacBook-Pro:vanadium apple$ VDLPATH=$PWD/src go test v.io/...
ok  	v.io/jiri	0.047s
# v.io/x/ref/services/syncbase/store/leveldb
../../../../../v.io/x/ref/services/syncbase/store/leveldb/db.go:10:11: fatal error: 'leveldb/c.h' file not found
 #include "leveldb/c.h"
          ^
1 error generated.
Please add /var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/106868686/root/.jiri_root/scripts to your PATH.
ERROR: jiri: unknown command "go"

Command jiri is a multi-purpose tool for multi-repo development.

Usage:
   jiri [flags] <command>

The jiri commands are:
   cl          Manage changelists for multiple projects
   import      Adds imports to .jiri_manifest file
   profile     Display information about installed profiles
   project     Manage the jiri projects
   rebuild     Rebuild all jiri tools
   snapshot    Manage project snapshots
   update      Update all jiri tools and projects
   which       Show path to the jiri tool
   runp        Run a command in parallel across jiri projects
   help        Display help for commands or topics
Run "jiri help [command]" for command usage.

The jiri additional help topics are:
   filesystem  Description of jiri file system layout
   manifest    Description of manifest files
Run "jiri help [topic]" for topic details.

The jiri flags are:
 -color=true
   Use color to format output.
 -v=false
   Print verbose output.

The global flags are:
 -metadata=<just specify -metadata to activate>
   Displays metadata for the program and exits.
 -time=false
   Dump timing information to stderr before exiting the program.
--- FAIL: TestBuildJiriLocally (0.12s)
	cmd.go:324: gosh: command failed: /Users/apple/workspace/go/bin/jiri go build -o /var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/327003861/jiri v.io/jiri/cmd/jiri
	cmd.go:325: 
		STDOUT
		----------------------------------------
		[ empty ]
	cmd.go:326: 
		STDERR
		----------------------------------------
		ERROR: jiri: unknown command "go"
		
		Command jiri is a multi-purpose tool for multi-repo development.
		
		Usage:
		   jiri [flags] <command>
		
		The jiri commands are:
		   cl          Manage changelists for multiple projects
		   import      Adds imports to .jiri_manifest file
		   profile     Display information about installed profiles
		   project     Manage the jiri projects
		   rebuild     Rebuild all jiri tools
		   snapshot    Manage project snapshots
		   update      Update all jiri tools and projects
		   which       Show path to the jiri tool
		   runp        Run a command in parallel across jiri projects
		   help        Display help for commands or topics
		Run "jiri help [command]" for command usage.
		
		The jiri additional help topics are:
		   filesystem  Description of jiri file system layout
		   manifest    Description of manifest files
		Run "jiri help [topic]" for topic details.
		
		The jiri flags are:
		 -color=true
		   Use color to format output.
		 -v=false
		   Print verbose output.
		
		The global flags are:
		 -metadata=<just specify -metadata to activate>
		   Displays metadata for the program and exits.
		 -time=false
		   Dump timing information to stderr before exiting the program.
		
	shell.go:119: goroutine 19 [running]:
		runtime/debug.Stack(0x0, 0x0, 0x0)
			/usr/local/go/src/runtime/debug/stack.go:24 +0x80
		v.io/x/lib/gosh.(*Shell).HandleErrorWithSkip(0xc82019e000, 0xf00000, 0xc8201d4020, 0x3)
			/Users/apple/workspace/go/src/v.io/x/lib/gosh/shell.go:119 +0x3a1
		v.io/x/lib/gosh.(*Cmd).handleError(0xc8201a6140, 0xf00000, 0xc8201d4020)
			/Users/apple/workspace/go/src/v.io/x/lib/gosh/cmd.go:328 +0x6dc
		v.io/x/lib/gosh.(*Cmd).Run(0xc8201a6140)
			/Users/apple/workspace/go/src/v.io/x/lib/gosh/cmd.go:203 +0x62
		v.io/jiri/cmd/jiri.TestBuildJiriLocally(0xc820196000)
			/Users/apple/workspace/go/src/v.io/jiri/cmd/jiri/bootstrap_jiri_test.go:67 +0x52b
		testing.tRunner(0xc820196000, 0x930d18)
			/usr/local/go/src/testing/testing.go:473 +0x98
		created by testing.RunTests
			/usr/local/go/src/testing/testing.go:582 +0x892
	shell.go:123: bootstrap_jiri_test.go:67: exit status 2
ERROR: /var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/449746480 already exists

Usage:
   bootstrap_jiri <root_dir>

A typical bootstrap workflow looks like this:

$ curl -s https://raw.githubusercontent.com/vanadium/go.jiri/master/scripts/bootstrap_jiri | bash -s myroot
$ export PATH=myroot/.jiri_root/scripts:$PATH
$ cd myroot
$ jiri import public https://vanadium.googlesource.com/manifest
$ jiri update
[17:20:14.70] >> move project "manifest" located in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/jiri-load646641369/manifest_965e96212e0ccdb9" to "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/682367951/manifest" and advance it to "HEAD"
[17:20:15.03] >> OK
[17:20:15.03] >> build tools: 
[17:20:15.30] >> OK
[17:20:16.60] >> move project "manifest" located in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/jiri-load419612795/manifest_147417ab9b794268" to "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/266613153/manifest" and advance it to "HEAD"
[17:20:16.97] >> OK
[17:20:16.97] >> build tools: 
[17:20:17.27] >> OK
Current Directory: /private/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/266613153/repo-test487620018
[17:20:18.54] >> move project "manifest" located in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/jiri-load270683821/manifest_761568336fb86bbd" to "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/500343683/manifest" and advance it to "HEAD"
[17:20:18.86] >> OK
[17:20:18.86] >> build tools: 
[17:20:19.17] >> OK
[17:20:20.91] >> move project "manifest" located in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/jiri-load942571216/manifest_910d440dbec77502" to "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/392223086/manifest" and advance it to "HEAD"
[17:20:21.23] >> OK
[17:20:21.23] >> build tools: 
[17:20:21.52] >> OK
[17:20:22.81] >> move project "manifest" located in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/jiri-load540755319/manifest_3b7cf0b69a6f5de7" to "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/191966269/manifest" and advance it to "HEAD"
[17:20:23.15] >> OK
[17:20:23.15] >> build tools: 
[17:20:23.41] >> OK
[17:20:26.35] >> move project "manifest" located in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/jiri-load019879762/manifest_76e8cad8a3b4049b" to "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/296055072/manifest" and advance it to "HEAD"
[17:20:26.76] >> OK
[17:20:26.77] >> build tools: 
[17:20:27.13] >> OK
[17:20:28.56] >> move project "manifest" located in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/jiri-load227833169/manifest_64258b23cb9d5866" to "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/117172615/manifest" and advance it to "HEAD"
[17:20:28.99] >> OK
[17:20:28.99] >> build tools: 
[17:20:29.33] >> OK
[17:20:31.91] >> move project "manifest" located in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/jiri-load812351908/manifest_a00e22ef78a9551f" to "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/758617122/manifest" and advance it to "HEAD"
[17:20:32.36] >> OK
[17:20:32.36] >> build tools: 
[17:20:32.74] >> OK
[17:20:37.88] >> move project "manifest" located in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/jiri-load055696571/manifest_cfebb65e854a7dd4" to "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/300199393/manifest" and advance it to "HEAD"
[17:20:38.30] >> OK
[17:20:38.30] >> build tools: 
[17:20:38.65] >> OK
[17:20:41.38] >> move project "manifest" located in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/jiri-load235497030/manifest_f517e53f040479e4" to "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/067177716/manifest" and advance it to "HEAD"
[17:20:41.73] >> OK
[17:20:41.73] >> build tools: 
[17:20:42.02] >> OK
[17:20:44.27] >> move project "manifest" located in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/jiri-load332984885/manifest_5d2caa76288d8f59" to "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/139321803/manifest" and advance it to "HEAD"
[17:20:44.67] >> OK
[17:20:44.68] >> build tools: 
[17:20:44.98] >> OK
[17:20:49.68] >> move project "manifest" located in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/jiri-load306311096/manifest_6e106e75f9e42538" to "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/251211798/manifest" and advance it to "HEAD"
[17:20:50.10] >> OK
[17:20:50.11] >> build tools: 
[17:20:50.46] >> OK
[17:20:51.39] >> move project "manifest" located in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/jiri-load748683327/manifest_dbf4439bbdd0b37c" to "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/894699461/manifest" and advance it to "HEAD"
[17:20:51.74] >> OK
[17:20:51.74] >> build tools: 
[17:20:52.01] >> OK
[17:20:56.62] >> move project "manifest" located in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/jiri-load165113978/manifest_9f92dbcd0e3ce5fe" to "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/035522056/manifest" and advance it to "HEAD"
[17:20:57.03] >> OK
[17:20:57.03] >> build tools: 
[17:20:57.34] >> OK
[17:21:01.91] >> move project "manifest" located in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/jiri-load213705956/manifest_16338b0f9602c537" to "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/802222946/manifest" and advance it to "HEAD"
[17:21:02.30] >> OK
[17:21:02.30] >> build tools: 
[17:21:02.65] >> OK
[17:21:04.15] >> move project "manifest" located in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/jiri-load378614011/manifest_ee4b09b8e9bb704c" to "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/195465761/manifest" and advance it to "HEAD"
[17:21:04.59] >> OK
[17:21:04.59] >> build tools: 
[17:21:04.96] >> OK
[17:21:05.76] >> create project "r.a" in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/195465761/r.a" and advance it to "HEAD"
[17:21:06.19] >> OK
[17:21:06.19] >> create project "r.b" in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/195465761/r.b" and advance it to "HEAD"
[17:21:06.60] >> OK
[17:21:06.60] >> create project "r.c" in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/195465761/r.c" and advance it to "HEAD"
[17:21:07.03] >> OK
[17:21:07.03] >> create project "r.t1" in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/195465761/r.t1" and advance it to "HEAD"
[17:21:07.47] >> OK
[17:21:07.47] >> create project "r.t2" in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/195465761/r.t2" and advance it to "HEAD"
[17:21:07.92] >> OK
[17:21:07.92] >> advance project "manifest" located in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/195465761/manifest" to "HEAD"
[17:21:08.34] >> OK
[17:21:08.34] >> build tools: 
[17:21:10.32] >> OK
[17:21:12.47] >> move project "manifest" located in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/jiri-load464477520/manifest_d278a5de235c88fd" to "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/381836270/manifest" and advance it to "HEAD"
[17:21:12.90] >> OK
[17:21:12.90] >> build tools: 
[17:21:13.24] >> OK
[17:21:31.57] >> move project "manifest" located in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/jiri-load088295866/manifest_a00dead53f8d23ed" to "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/374784840/manifest" and advance it to "HEAD"
[17:21:31.98] >> OK
[17:21:31.98] >> build tools: 
[17:21:32.29] >> OK
[17:21:33.09] >> create project "r.a" in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/374784840/r.a" and advance it to "HEAD"
[17:21:33.50] >> OK
[17:21:33.50] >> create project "r.b" in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/374784840/r.b" and advance it to "HEAD"
[17:21:33.93] >> OK
[17:21:33.93] >> create project "r.c" in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/374784840/r.c" and advance it to "HEAD"
[17:21:34.35] >> OK
[17:21:34.35] >> create project "r.t1" in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/374784840/r.t1" and advance it to "HEAD"
[17:21:34.82] >> OK
[17:21:34.82] >> create project "r.t2" in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/374784840/r.t2" and advance it to "HEAD"
[17:21:35.29] >> OK
[17:21:35.29] >> advance project "manifest" located in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/374784840/manifest" to "HEAD"
[17:21:35.70] >> OK
[17:21:35.70] >> build tools: 
[17:21:37.69] >> OK
[17:21:48.82] >> move project "manifest" located in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/jiri-load080425765/manifest_1fa58a831de33bb1" to "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/593886011/manifest" and advance it to "HEAD"
[17:21:49.24] >> OK
[17:21:49.24] >> build tools: 
[17:21:49.57] >> OK
[17:21:50.14] >> move project "manifest" located in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/jiri-load569049667/manifest_c3d17b1920cdd1de" to "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/052479017/manifest" and advance it to "HEAD"
[17:21:50.58] >> OK
[17:21:50.58] >> build tools: 
[17:21:50.92] >> OK
[17:21:51.47] >> move project "manifest" located in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/jiri-load308202396/manifest_adf50629b8ec7173" to "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/864596314/manifest" and advance it to "HEAD"
[17:21:51.86] >> OK
[17:21:51.86] >> build tools: 
[17:21:52.23] >> OK
[17:21:52.87] >> create project "test-remote-project-1" in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/864596314/test-local-project-1" and advance it to "HEAD"
[17:21:53.31] >> OK
[17:21:53.31] >> create project "test-remote-project-2" in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/864596314/test-local-project-2" and advance it to "HEAD"
[17:21:53.74] >> OK
[17:21:53.74] >> advance project "manifest" located in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/864596314/manifest" to "HEAD"
[17:21:54.16] >> OK
[17:21:54.16] >> build tools: 
[17:21:55.20] >> OK
[17:21:58.95] >> move project "manifest" located in "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/jiri-load299100926/manifest_98c8017bdc853ffd" to "/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/792628460/manifest" and advance it to "HEAD"
[17:21:59.40] >> OK
[17:21:59.40] >> build tools: 
[17:21:59.73] >> OK
# binary
/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/859613970/jiri
# script
/Users/apple/workspace/go/src/v.io/jiri/scripts/jiri
FAIL
FAIL	v.io/jiri/cmd/jiri	139.792s
?   	v.io/jiri/collect	[no test files]
ok  	v.io/jiri/gerrit	0.020s
?   	v.io/jiri/gitutil	[no test files]
ok  	v.io/jiri/googlesource	0.018s
ok  	v.io/jiri/jenkins	0.027s
?   	v.io/jiri/jiritest	[no test files]
ok  	v.io/jiri/profiles	1.293s
ok  	v.io/jiri/profiles/profilescmdline	25.572s
?   	v.io/jiri/profiles/profilescmdline/internal/example	[no test files]
?   	v.io/jiri/profiles/profilescmdline/internal/i1	[no test files]
?   	v.io/jiri/profiles/profilescmdline/internal/i2	[no test files]
ok  	v.io/jiri/profiles/profilesmanager	0.017s
ok  	v.io/jiri/profiles/profilesreader	2.576s
?   	v.io/jiri/profiles/profilesutil	[no test files]
ok  	v.io/jiri/project	59.358s
?   	v.io/jiri/retry	[no test files]
ok  	v.io/jiri/runutil	29.557s
?   	v.io/jiri/tool	[no test files]
ok  	v.io/v23	0.021s
ok  	v.io/v23/context	0.133s
ok  	v.io/v23/conventions	0.067s
ok  	v.io/v23/discovery	0.025s
?   	v.io/v23/flow	[no test files]
ok  	v.io/v23/flow/message	0.087s
ok  	v.io/v23/glob	0.014s
ok  	v.io/v23/i18n	0.014s
?   	v.io/v23/logging	[no test files]
?   	v.io/v23/namespace	[no test files]
ok  	v.io/v23/naming	0.799s
?   	v.io/v23/options	[no test files]
?   	v.io/v23/query	[no test files]
--- FAIL: TestSelect (1.47s)
	query_test.go:2255: query: select k from Customer where v.InvoiceDate = Time("2006-01-02 15:04:05 MST", "2015-03-17 11:14:04 PDT"); got [][]any{}, want [][]any{{"002001"}}
	query_test.go:2284: query: select k from Customer where v.InvoiceDate = Time("2006-01-02 15:04:05 MST", "2015-03-17 11:14:04 PDT"); got [], want [[RawBytes{Version81, string, 06303032303031}]]
FAIL
FAIL	v.io/v23/query/engine	1.952s
?   	v.io/v23/query/engine/datasource	[no test files]
--- FAIL: TestSelect (0.83s)
	query_test.go:2282: query: select k from Customer where v.InvoiceDate = Time("2006-01-02 15:04:05 MST", "2015-03-17 11:14:04 PDT"); got [][]any{}, want [][]any{{"002001"}}
FAIL
FAIL	v.io/v23/query/engine/internal	1.018s
?   	v.io/v23/query/engine/internal/conversions	[no test files]
ok  	v.io/v23/query/engine/internal/query_checker	0.119s
ok  	v.io/v23/query/engine/internal/query_functions	0.172s
ok  	v.io/v23/query/engine/internal/query_parser	0.107s
?   	v.io/v23/query/engine/internal/test	[no test files]
?   	v.io/v23/query/engine/public	[no test files]
ok  	v.io/v23/query/pattern	0.015s
ok  	v.io/v23/query/syncql	0.077s
ok  	v.io/v23/rpc	0.050s
?   	v.io/v23/rpc/reserved	[no test files]
?   	v.io/v23/rpc/version	[no test files]
ok  	v.io/v23/security	3.470s
ok  	v.io/v23/security/access	0.095s
?   	v.io/v23/security/access/internal	[no test files]
?   	v.io/v23/services/appcycle	[no test files]
ok  	v.io/v23/services/application	0.056s
?   	v.io/v23/services/binary	[no test files]
?   	v.io/v23/services/build	[no test files]
?   	v.io/v23/services/device	[no test files]
ok  	v.io/v23/services/groups	0.026s
?   	v.io/v23/services/logreader	[no test files]
?   	v.io/v23/services/mounttable	[no test files]
?   	v.io/v23/services/permissions	[no test files]
?   	v.io/v23/services/pprof	[no test files]
?   	v.io/v23/services/repository	[no test files]
?   	v.io/v23/services/stats	[no test files]
?   	v.io/v23/services/syncbase	[no test files]
?   	v.io/v23/services/tidyable	[no test files]
?   	v.io/v23/services/vtrace	[no test files]
?   	v.io/v23/services/wakeup	[no test files]
?   	v.io/v23/services/watch	[no test files]
FAIL	v.io/v23/syncbase [build failed]
?   	v.io/v23/syncbase/crtestutil	[no test files]
FAIL	v.io/v23/syncbase/featuretests [build failed]
FAIL	v.io/v23/syncbase/util [build failed]
ok  	v.io/v23/uniqueid	0.032s
ok  	v.io/v23/vdl	26.212s
?   	v.io/v23/vdl/vdltest	[no test files]
?   	v.io/v23/vdl/vdltest/internal/vdltestgen	[no test files]
?   	v.io/v23/vdlroot	[no test files]
ok  	v.io/v23/vdlroot/math	0.017s
ok  	v.io/v23/vdlroot/signature	0.013s
ok  	v.io/v23/vdlroot/time	0.015s
ok  	v.io/v23/vdlroot/vdltool	0.014s
ok  	v.io/v23/verror	0.094s
ok  	v.io/v23/vom	55.194s
ok  	v.io/v23/vom/internal	0.023s
?   	v.io/v23/vom/internal/gen	[no test files]
?   	v.io/v23/vom/vomtest	[no test files]
?   	v.io/v23/vom/vomtest/internal/vomforever	[no test files]
?   	v.io/v23/vom/vomtest/internal/vomtestgen	[no test files]
ok  	v.io/v23/vtrace	0.013s
?   	v.io/x/lib/cmd/linewrap	[no test files]
ok  	v.io/x/lib/cmdline	10.865s
?   	v.io/x/lib/dbutil	[no test files]
ok  	v.io/x/lib/envvar	0.014s
ok  	v.io/x/lib/gcm	0.017s
ok  	v.io/x/lib/gosh	28.660s
?   	v.io/x/lib/gosh/internal/gosh_example	[no test files]
?   	v.io/x/lib/gosh/internal/gosh_example_client	[no test files]
?   	v.io/x/lib/gosh/internal/gosh_example_lib	[no test files]
?   	v.io/x/lib/gosh/internal/gosh_example_server	[no test files]
?   	v.io/x/lib/gosh/internal/hello_world	[no test files]
?   	v.io/x/lib/host	[no test files]
ok  	v.io/x/lib/ibe	4.658s
ok  	v.io/x/lib/lookpath	0.021s
ok  	v.io/x/lib/metadata	0.964s
ok  	v.io/x/lib/netconfig	0.019s
ok  	v.io/x/lib/netstate	0.020s
ok  	v.io/x/lib/nsync	18.955s
ok  	v.io/x/lib/set	0.013s
ok  	v.io/x/lib/simplemr	1.486s
ok  	v.io/x/lib/textutil	0.179s
ok  	v.io/x/lib/timing	0.012s
ok  	v.io/x/lib/toposort	0.011s
ok  	v.io/x/lib/vlog	0.038s
ok  	v.io/x/ref	0.014s
ok  	v.io/x/ref/cmd/gclogs	0.032s
ok  	v.io/x/ref/cmd/mounttable	0.096s
?   	v.io/x/ref/cmd/namespace	[no test files]
FAIL	v.io/x/ref/cmd/principal [build failed]
?   	v.io/x/ref/cmd/sb	[no test files]
?   	v.io/x/ref/cmd/sb/commands	[no test files]
?   	v.io/x/ref/cmd/sb/dbutil	[no test files]
?   	v.io/x/ref/cmd/sb/internal/demodb	[no test files]
ok  	v.io/x/ref/cmd/sb/internal/reader	0.047s
ok  	v.io/x/ref/cmd/sb/internal/writer	0.041s
?   	v.io/x/ref/cmd/uniqueid	[no test files]
--- FAIL: TestVDLGenerator (3.42s)
	shell.go:628: Built executable: /var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/236207107/vdl
	cmd.go:324: gosh: command failed: /var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/236207107/vdl generate --lang=go --go-out-dir=/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/842130733 ../../lib/vdl/testdata/base
	cmd.go:325: 
		STDOUT
		----------------------------------------
		[ empty ]
	cmd.go:326: 
		STDERR
		----------------------------------------
		ERROR: 
		#0 /Users/apple/workspace/go/src/v.io/x/ref/lib/vdl/testdata/base: can't deduce package path (no matching src dirs)
		#1 can't resolve "../../lib/vdl/testdata/base" to any packages
		   (run with "vdl -v" for verbose logging or "vdl help" for help)
		
	shell.go:119: goroutine 142 [running]:
		runtime/debug.Stack(0x0, 0x0, 0x0)
			/usr/local/go/src/runtime/debug/stack.go:24 +0x80
		v.io/x/lib/gosh.(*Shell).HandleErrorWithSkip(0

````

**Comment by razvanm** [comment]
@joeblew99 Can you please try the instructions I indicated in an empty Go workspace? The https://github.com/vanadium/core repo doesn't have depend on leveldb. You can see on Travis an example ([146697133](https://travis-ci.org/vanadium/core/builds/146697133)) of how things should look like.

**Comment by razvanm** [comment]
Quick note: I update the repo to also include the support for Java so things changed a little. Now there is a `Makefile` that contains some targets to build (`make all`) and run the tests (`make test` and `make test-java`).

**Comment by joeblew99** [comment]
thanks @razvanm  for the heads up. i will try out the make file

**Comment by gedw99** [comment]
fixed thanks.
