### ISSUE TITLE
typecache.go:59] closing ready chan for nil flow

### ISSUE THREAD

**Issue by yasushi-saito** [vanadium/core#89]
Does this failure ring any bell? There's not much context other than the error stack:
```
 --- FAIL: TestTidy/S3ValidateErrors (2.46s)
        util.go:163: got I0118 20:44:43.067836    6688 funcs.go:35] goroutine 177 [running]:
            v.io/x/lib/vlog.infoStack(0xc00019e340, 0x84dd2a8c6fb63e00)
            	external/io_v_x_lib/vlog/log.go:211 +0xc4
            v.io/x/lib/vlog.InfoStack(0x0)
            	external/io_v_x_lib/vlog/funcs.go:35 +0x36
            v.io/x/ref/runtime/internal/rpc.(*typeCache).writer.func1(0x0, 0x0, 0xc0008f96e0)
            	external/io_v/x/ref/runtime/internal/rpc/typecache.go:58 +0x35b
            v.io/x/ref/runtime/internal/rpc.(*client).tryConnectToServer(0xc000419570, 0xc0000bd500, 0x0, 0x7ffe388f0af5, 0x1a, 0xc0002c3200, 0x58, 0x46b214, 0xb, 0x0, ...)
            	external/io_v/x/ref/runtime/internal/rpc/client.go:483 +0x6ca
            created by v.io/x/ref/runtime/internal/rpc.(*client).tryConnectToName
            	external/io_v/x/ref/runtime/internal/rpc/client.go:375 +0x10b8
            I0118 20:44:43.068911    6688 typecache.go:59] closing ready chan for nil flow
```

**Comment by yasushi-saito** [comment]
Or is this some junk log message that we can ignore?

**Comment by cosnicolaou** [comment]
These are now gone.
